# Generated by Django 4.0.5 on 2023-05-07 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AdministracionApp', '0001_initial'),
        ('AdmCajasApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='manuales',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_manual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manuales',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_manual', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errores',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.grupoerror'),
        ),
        migrations.AddField(
            model_name='errores',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdministracionApp.sucursales'),
        ),
        migrations.AddField(
            model_name='errores',
            name='user_update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update_errores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='errores',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_create_errores', to=settings.AUTH_USER_MODEL),
        ),
    ]
